### ISSUE TITLE
Unable to see attachments on private wiki

### ISSUE THREAD

**Issue by wild-paul** [f0y/redmine_private_wiki#7]
I have admin priveleges, but when I click on private wiki attachnet, I see following:

`403 You are not authorized to access this page.`

Solution is very simple, right code of **visible_with_private_wiki** is below
Note **project**,  not **~~@project~~** as parameter of **is_private_page_visible?**

``` ruby
  def visible_with_private_wiki?(user)
    if self.private and !is_private_page_visible?(project)
      return false
    end
    visible_without_private_wiki?(user)
  end
```

**Comment by f0y** [comment]
Great! Feel free to post other bugs.

**Comment by wild-paul** [comment]
No more ))
Спасибо за хороший плагин, я уже сам чуть не собрался писать. 
Багов пока больше нет. Могу подсказать еще пару пожеланий:
- в списке страниц wiki/index видеть их статус( и даже оттуда и переключать). Так удобнее представить общую картину
- там же, может быть, спрятать от пользователя названия страниц, которые он видеть не может. Но тут надо аккуратно, чтобы не сломать иерархическое отображение

**Comment by f0y** [comment]
It's good idea to add some features but I should backport improvements from chiliproject fork and add unit-tests as soon as possible. Adding tests is more important than adding any feature, cause the plugin deals with the redmine access control system, so the plugin helps securing valuable data. 
Unfortunately,  I do not have enough time to do this, because I am preparing my graduation paper.

**Comment by f0y** [comment]
Please add your issues to the tracker.
